### ISSUE TITLE
Create draft schema for the app 

### ISSUE THREAD

**Issue by puneetbhagat** [iOSBootcamp2017-Team7/ConnectedAlarmApp#2]

**Comment by uttamsingh** [comment]
Create wiki for the same https://github.com/iOSBootcamp2017-Team7/ConnectedAlarmApp/wiki/Model-Entities

**Comment by puneetbhagat** [comment]
@uttamsingh - Reviewed the data model. The initial design looks good. I have made few minor changes and have added my comments as _[pb: <comment>]_
